spring:
    hadoop:
        fsUri: hdfs://localhost:8020
        resourceManagerHost: localhost
    yarn:
        appName: yarn
        applicationDir: /app/yarn/
        client:
            files:
              - "file:dist/target/dist/container-0.1.0.jar"
              - "file:dist/target/dist/appmaster-0.1.0.jar"
            launchcontext:
                archiveFile: appmaster-0.1.0.jar
        appmaster:
            containerCount: 1
            launchcontext:
                archiveFile: container-0.1.0.jar